# libgarnish
# Nik Sultana, University of Pennsylvania, November 2017


garnish_M100.h : garnish.h garnish_M100_config.h
	$(CC) -include garnish_M100_config.h $(CFLAGS) -E garnish.h -o $@

garnish_S1000.h : garnish.h garnish_S1000_config.h
	$(CC) -include garnish_S1000_config.h $(CFLAGS) -E garnish.h -o $@

garnish_P100.h : garnish.h garnish_P100_config.h
	$(CC) -include garnish_P100_config.h $(CFLAGS) -E garnish.h -o $@

garnish_hash_M100.o : garnish_hash.c
	$(CC) -include stdint.h -include garnish_M100_config.h -include garnish.h -c $(CFLAGS) garnish_hash.c -o $@

garnish_M100.o : garnish.c
	$(CC) -include stdint.h -include garnish_M100_config.h -include garnish.h -c $(CFLAGS) garnish.c -o $@

garnish_hash_S1000.o : garnish_hash.c
	$(CC) -include stdint.h -include garnish_S1000_config.h -include garnish.h -c $(CFLAGS) garnish_hash.c -o $@

garnish_S1000.o : garnish.c
	$(CC) -include stdint.h -include garnish_S1000_config.h -include garnish.h -c $(CFLAGS) garnish.c -o $@

garnish_hash_P100.o : garnish_hash.c
	$(CC) -include stdint.h -include garnish_P100_config.h -include garnish.h -c $(CFLAGS) garnish_hash.c -o $@

garnish_P100.o : garnish.c
	$(CC) -include stdint.h -include garnish_P100_config.h -include garnish.h -c $(CFLAGS) garnish.c -o $@

singlethreaded_test.o : singlethreaded_test.c garnish_S1000.o garnish.h garnish_S1000_config.h
	$(CC) -include garnish_S1000_config.h $(CFLAGS) -c singlethreaded_test.c -o $@

multithreaded_test.o : multithreaded_test.c garnish_M100.o garnish.h garnish_M100_config.h
	$(CC) -include garnish_M100_config.h $(CFLAGS) -c multithreaded_test.c -o $@

multiprocess_test.o : multiprocess_test.c garnish_P100.o garnish_M100_config.h garnish_P100.h
	$(CC) $(CFLAGS) -c multiprocess_test.c -o $@

garnish_test: singlethreaded_test.o garnish_S1000.o garnish_hash_S1000.o
	$(CC) $(CFLAGS) singlethreaded_test.o garnish_S1000.o garnish_hash_S1000.o -o $@

garnish_multithreaded: multithreaded_test.o garnish_M100.o garnish_hash_M100.o
	$(CC) $(CFLAGS) -lpthread $^ -o $@

garnish_2tables: 2tables.c garnish_M100.o garnish_S1000.o garnish_hash_S1000.o garnish_hash_M100.o
	make garnish_M100.h
	make garnish_S1000.h
	$(CC) $(CFLAGS) -lpthread $^ -o $@

garnish_multiprocess: multiprocess_test.o garnish_P100.o garnish_hash_P100.o
	$(CC) $(CFLAGS) $^ -o $@

# NOTE using uthash is optional. To use it clone the uthash repo in the UTHASH directory, and build the uthash-related targets. See DEVELOPER.md for more info.
UTHASH=uthash
garnish_M100_uthash.o : garnish_uthash.c
	$(CC) -include stdint.h -include garnish_M100_config.h -include garnish.h -I$(UTHASH)/include -c $(CFLAGS) garnish_uthash.c -o $@

garnish_multithreaded_uthash: multithreaded_test.o garnish_M100_uthash.o garnish_hash_M100.o
	$(CC) $(CFLAGS) -lpthread $^ -o $@
